[tool.ruff]
# 行长度限制
line-length = 100

# Python 版本
target-version = "py311"

# 排除目录
exclude = [
    ".venv",
    "build",
    "dist",
    "__pycache__",
    "*.egg-info",
]

[tool.ruff.lint]
# 启用的规则集
select = [
    "E",      # pycodestyle errors (E4, E7, E9)
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort (import 排序)
    "N",      # pep8-naming (命名规范)
    "UP",     # pyupgrade (语法升级)
    "B",      # flake8-bugbear (常见错误)
    "SIM",    # flake8-simplify (简化建议)
    "C90",    # mccabe (复杂度检查)
    "PL",     # pylint
    "RUF",    # ruff 特定规则
    "S",      # flake8-bandit (安全检查)
    "PTH",    # flake8-use-pathlib (推荐用 pathlib)
]

# 忽略的规则
ignore = [
    "E501",    # line-too-long (已在 line-length 设置)
    "PLR0913", # too-many-arguments
    "S101",    # assert 语句 (测试中常用)
]

# 每个文件的特殊规则
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # 允许未使用的导入
"test_*.py" = ["S101"]    # 测试文件允许 assert

# 复杂度配置
[tool.ruff.lint.mccabe]
max-complexity = 10

# import 排序配置
[tool.ruff.lint.isort]
known-first-party = ["app", "gui"]

# 格式化配置
[tool.ruff.format]
quote-style = "double"           # 使用双引号
indent-style = "space"           # 使用空格缩进
skip-magic-trailing-comma = false
line-ending = "auto"